schema_version = "1.0.0"

id = "coaster_mixer"
version = "0.3.0-alpha.6"
name = "Coaster Mixer"
tagline = "Author and drive curve-based rollercoasters"
maintainer = "Coaster Mixer contributors"
type = "add-on"

blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Animation"]
